### ISSUE TITLE
error:Cannot query field "allContentfulProduct" on type "Query"

### ISSUE THREAD

**Issue by jiangwalle** [rohitguptab/OneShopper#1]
Hi there, I'm getting this error by following the readme to start. Is it because I haven't initialized contentful with some sample data? And how can we do that? Thanks.

**Comment by rohitguptab** [comment]
Hello @jiangwalle,

For adding contentful to your website, Create a .env file on your root directory and add following keys:
spaceId=''
accessToken=''
snipcart=''

After that, follow this [link](https://itnext.io/content-management-with-gatsby-netlify-and-contentful-70f03de41602) to add content in your contentful and you are ready to go.

**Comment by LB22** [comment]
I had the same problem but didn't find any fix. [This](https://stackoverflow.com/a/61586076/13765158) answer from stackoverflow did it for me.
Just create a content entry for all your different models otherwise your website has no content and therefore can't process the query
