### ISSUE TITLE
Contentful format

### ISSUE THREAD

**Issue by marquez138** [rohitguptab/OneShopper#2]
Hi im stuck as to how i format my contentful content to correctly use this project. For example  i noticed theres additional attributes for the image (width,height,src,srcSet). Is there away for me to add these attributes on contentful? Sorry a im a bit new to contentful and grapghQl

**Comment by rohitguptab** [comment]
Hello @marquez138 

Sorry for the late response.

Actually, First of all, you need to configure contentful and Snipcart in your setup as per below steps.

For adding contentful to your website, Create a .env file on your root directory and add following keys:
**spaceId** =''
**accessToken** =''
**snipcart** =''


Follow below links it might help you to understand contentful.
[Contentful](https://www.contentful.com/r/knowledgebase/creating-a-website-in-five-minutes/)
[snipcart](https://www.gatsbyjs.org/packages/gatsby-plugin-snipcart/)

Let me know if you still have any query.
