### ISSUE TITLE
SpaceId:undefined and accessToken:undefined

### ISSUE THREAD

**Issue by amanmishra1321** [rohitguptab/OneShopper#20]
Problems with gatsby-source-contentful plugin options:
spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required
Bro I am new to gatsby by I think you haven't mention spaceId and accessToken in gatsby-config.js file and I don't have idea what to write inside it?

**Comment by rohitguptab** [comment]
Hello @AmanMishra1321 ,

You have to create contentful and snipcart accounts.

Please follow this below blog. if still not work then let me know.
 
[https://rohitgupta.netlify.app/oneshopper-gatsby-site](https://rohitgupta.netlify.app/oneshopper-gatsby-site)
