### ISSUE TITLE
Error: gatsby deploy - error in store.js

### ISSUE THREAD

**Issue by Teegreat** [rohitguptab/OneShopper#3]
I have been unable to run gatsby develop successfully.
![error](https://user-images.githubusercontent.com/33378366/62740677-6360de00-ba30-11e9-85d9-1f90e55e01f8.PNG)
![error](https://user-images.githubusercontent.com/33378366/62740721-868b8d80-ba30-11e9-85a1-26a4d86044d3.PNG)

**Comment by rohitguptab** [comment]
Hello @Teegreat 

Sorry for the late response.

Actually, First of all, you need to configure contentful and Snipcart in your setup as per below steps.

For adding contentful to your website, Create a .env file on your root directory and add following keys:
**spaceId** =''
**accessToken** =''
**snipcart** =''


For more information, you can follow the below links.
[Contentful](https://www.contentful.com/r/knowledgebase/creating-a-website-in-five-minutes/)
[snipcart](https://www.gatsbyjs.org/packages/gatsby-plugin-snipcart/)

Let me know if you still have any query.
